from dataclasses import dataclass
from pathlib import Path
import tkinter as tk
from tkinter import filedialog, messagebox, simpledialog
from ultralytics import YOLO


@dataclass
class TrainConfig:
    data_yaml: str = "datasets/yolo_data/dataset.yaml"
    model_name: str = "yolo26n.pt"
    epochs: int = 50
    imgsz: int = 640
    batch: int = 16
    device: int = 0          # GPU 0
    workers: int = 0         # importante en Windows
    project: str = "runs/sperm_yolo"
    name: str = "exp1"


def train_yolo(cfg: TrainConfig):
    data_yaml = Path(cfg.data_yaml)
    if not data_yaml.exists():
        raise FileNotFoundError(f"Dataset YAML not found: {data_yaml}")

    print(f"Loading model: {cfg.model_name}")
    model = YOLO(cfg.model_name)

    print(f"Training with dataset: {data_yaml}")
    results = model.train(
        data=str(data_yaml),
        epochs=cfg.epochs,
        imgsz=cfg.imgsz,
        batch=cfg.batch,
        device=cfg.device,
        workers=cfg.workers,
        project=cfg.project,
        name=cfg.name,
        patience=20,
    )

    print("Training complete.")
    return model, results


def _init_tk():
    """Create and immediately hide a Tk root window."""
    root = tk.Tk()
    root.withdraw()
    try:
        root.attributes("-topmost", True)
    except Exception:
        pass
    return root


def _select_dataset_yaml():
    """Ask the user to select the dataset.yaml file."""
    print("\n" + "=" * 60)
    print("📄  STEP 1: Select dataset.yaml file")
    print("=" * 60)
    print("Please choose the dataset.yaml file generated by 3_convert_to_yolo.py.")

    default_yaml = Path("datasets/yolo_data/dataset.yaml")
    default_dir = (
        str(default_yaml.parent.resolve())
        if default_yaml.parent.exists()
        else "."
    )

    root = _init_tk()
    yaml_file = filedialog.askopenfilename(
        title="Select dataset.yaml file",
        initialdir=default_dir,
        filetypes=[("YAML files", "*.yaml *.yml"), ("All files", "*.*")],
    )
    root.destroy()

    if not yaml_file:
        print("❌  No file selected. Exiting.")
        return None

    yaml_path = Path(yaml_file)
    if not yaml_path.exists():
        print(f"❌  File not found: {yaml_path}")
        return None

    print(f"✅  Dataset YAML : {yaml_path}")
    return str(yaml_path)


def _select_model_size():
    """Ask the user to choose a YOLO model size."""
    print("\n" + "=" * 60)
    print("🤖  STEP 2: Choose YOLO model size")
    print("=" * 60)

    _MODEL_MAP = {
        "n — Nano   (fastest, least accurate)":  "yolov8n.pt",
        "s — Small  (fast, good accuracy)":      "yolov8s.pt",
        "m — Medium (balanced)":                 "yolov8m.pt",
        "l — Large  (slower, more accurate)":    "yolov8l.pt",
    }

    root = _init_tk()

    dialog = tk.Toplevel(root)
    dialog.title("Select YOLO Model Size")
    dialog.resizable(False, False)
    try:
        dialog.attributes("-topmost", True)
    except Exception:
        pass

    tk.Label(
        dialog,
        text="Choose a YOLO model size for training:\n",
        font=("Segoe UI", 11),
        pady=10,
        padx=20,
    ).pack()

    selected = tk.StringVar(value=list(_MODEL_MAP.keys())[1])  # default: small
    for label in _MODEL_MAP:
        tk.Radiobutton(
            dialog,
            text=label,
            variable=selected,
            value=label,
            font=("Segoe UI", 10),
            padx=20,
        ).pack(anchor="w")

    def _confirm():
        dialog.destroy()

    tk.Button(
        dialog,
        text="Confirm",
        command=_confirm,
        font=("Segoe UI", 10, "bold"),
        padx=20,
        pady=6,
    ).pack(pady=(12, 16))

    root.wait_window(dialog)
    model_name = _MODEL_MAP[selected.get()]
    root.destroy()

    print(f"✅  Model size : {selected.get().strip()}")
    print(f"    Weights   : {model_name}")
    return model_name


def _ask_training_params():
    """Ask the user for training hyper-parameters."""
    print("\n" + "=" * 60)
    print("⚙️   STEP 3: Configure training parameters")
    print("=" * 60)

    root = _init_tk()
    epochs = simpledialog.askinteger(
        "Epochs",
        "Number of training epochs:\n(More epochs = longer training, potentially better model)\nDefault: 50",
        initialvalue=50,
        minvalue=1,
        maxvalue=10000,
        parent=root,
    )
    root.destroy()
    if epochs is None:
        epochs = 50
        print(f"⚠️   Using default epochs: {epochs}")
    else:
        print(f"✅  Epochs : {epochs}")

    root2 = _init_tk()
    batch = simpledialog.askinteger(
        "Batch Size",
        "Batch size (images per training step):\n"
        "Lower values use less GPU memory.\nDefault: 16",
        initialvalue=16,
        minvalue=1,
        maxvalue=512,
        parent=root2,
    )
    root2.destroy()
    if batch is None:
        batch = 16
        print(f"⚠️   Using default batch size: {batch}")
    else:
        print(f"✅  Batch  : {batch}")

    root3 = _init_tk()
    imgsz = simpledialog.askinteger(
        "Image Size",
        "Input image size in pixels (square):\nDefault: 640",
        initialvalue=640,
        minvalue=32,
        maxvalue=1280,
        parent=root3,
    )
    root3.destroy()
    if imgsz is None:
        imgsz = 640
        print(f"⚠️   Using default image size: {imgsz}")
    else:
        print(f"✅  Image size : {imgsz}")

    return epochs, batch, imgsz


if __name__ == "__main__":
    print("\n" + "🔬 " * 20)
    print("  SPERM DETECTION — YOLO Model Trainer")
    print("🔬 " * 20)

    data_yaml = _select_dataset_yaml()
    if data_yaml is None:
        raise SystemExit(1)

    model_name = _select_model_size()
    epochs, batch, imgsz = _ask_training_params()

    cfg = TrainConfig(
        data_yaml=data_yaml,
        model_name=model_name,
        epochs=epochs,
        imgsz=imgsz,
        batch=batch,
    )

    print("\n" + "=" * 60)
    print("📋  Training Configuration Summary")
    print("=" * 60)
    print(f"  📄 Dataset YAML   : {cfg.data_yaml}")
    print(f"  🤖 Model          : {cfg.model_name}")
    print(f"  🔁 Epochs         : {cfg.epochs}")
    print(f"  📦 Batch size     : {cfg.batch}")
    print(f"  🖼️   Image size    : {cfg.imgsz}")
    print(f"  💾 Output project : {cfg.project}/{cfg.name}")
    print("=" * 60)

    root = _init_tk()
    proceed = messagebox.askyesno(
        "Confirm Training",
        f"Ready to start training.\n\n"
        f"Dataset : {Path(cfg.data_yaml).name}\n"
        f"Model   : {cfg.model_name}\n"
        f"Epochs  : {cfg.epochs}\n"
        f"Batch   : {cfg.batch}\n"
        f"ImgSz   : {cfg.imgsz}\n\n"
        "This may take a long time. Proceed?",
    )
    root.destroy()

    if not proceed:
        print("❌  Cancelled by user.")
        raise SystemExit(0)

    print("\n🚀  Starting training...\n")
    model, results = train_yolo(cfg)

    results_path = Path(cfg.project) / cfg.name
    print(f"\n✅  Training complete!")
    print(f"    Best weights : {results_path / 'weights' / 'best.pt'}")
    print(f"    Results      : {results_path}")